name: USBIP Mounter
slug: usbip
startup: services
url: https://github.com/irakhlin/hassio-usbip-mounter
panel_icon: mdi:usb
usbip: true
usb: true
kernel_modules: true
host_network: true
apparmor: false
version: 1.4.0
description: USBIP Client Handler to attach USBIP devices to Hassio
init: false
full_access: true
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
devices:
  - /dev/mem
schema:
  devices:
    - server_address: match(^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$)
      bus_id: str
options:
  devices: []
